// <auto-generated />
namespace MyWebEntityLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class updtdtbs5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updtdtbs5));
        
        string IMigrationMetadata.Id
        {
            get { return "201502202136259_updtdtbs5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
